# Generated by Django 5.2.4 on 2025-07-12 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_objeto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='objetos_encontrados/')),
                ('estado', models.CharField(default='encontrado', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_encontrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
