# Generated by Django 5.2.4 on 2025-07-12 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_objetoencontrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoencontrado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
