# Generated by Django 5.2.4 on 2025-07-12 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_objetoencontrado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetoencontrado',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='objetoencontrado',
            name='estado',
            field=models.CharField(default='encontrado', max_length=50),
        ),
        migrations.AlterField(
            model_name='objetoencontrado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_encontrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
